### PR TITLE
Remove unused imports.

### PR DESCRIPTION
**Pull request by olafurpg**
Was gonna work on #1039 but hit on several problems that prevent us from
enabling this by default.

### CODE REVIEW

**Comment by xeno-by** [comment]
Is the failure spurious?

**Comment by olafurpg** [comment]
Yes the error is spurious, I restarted the job but we should be safe to merge.

**Comment by olafurpg** [comment]
Restarting still reproduces

> There is insufficient memory for the Java Runtime Environment to continue.

I wonder why this starts now, maybe Travis CI is under heavy usage. I propose we let this wait a bit.

**Comment by olafurpg** [comment]
The failures consistently happen for 2.12.2 with JS=true. Interesting, we may want to delete that entry of the build in case the failures continue. We should then investigate the option of getting more powerful machines to run our CI.

**Pull request merged**
