### PR TITLE
Fixed NoSuchElementException when parse Unit with infix operations

### LINKED ISSUE #492: Parser: java.util.NoSuchElementException
Parsing: https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/hlist.scala

Stacktrace:

```
java.util.NoSuchElementException: head of empty list
  scala.collection.immutable.Nil$.head(List.scala:420)
  scala.collection.immutable.Nil$.head(List.scala:417)
  scala.meta.internal.parsers.ScalametaParser.loop$5(ScalametaParser.scala:1868)
  scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:1903)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1$$anonfun$41.apply(ScalametaParser.scala:1594)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1$$anonfun$41.apply(ScalametaParser.scala:1594)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1.apply(ScalametaParser.scala:1594)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1.apply(ScalametaParser.scala:1522)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1522)
  scala.meta.internal.parsers.ScalametaParser.expr(ScalametaParser.scala:1499)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$patDefOrDcl$1.apply(ScalametaParser.scala:2939)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$patDefOrDcl$1.apply(ScalametaParser.scala:2923)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.patDefOrDcl(ScalametaParser.scala:2923)
  scala.meta.internal.parsers.ScalametaParser.defOrDclOrSecondaryCtor(ScalametaParser.scala:2907)
  scala.meta.internal.parsers.ScalametaParser.localDef(ScalametaParser.scala:3517)
  scala.meta.internal.parsers.ScalametaParser.blockStatSeq(ScalametaParser.scala:3551)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$block$1.apply(ScalametaParser.scala:2095)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$block$1.apply(ScalametaParser.scala:2095)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser.block(ScalametaParser.scala:2094)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$blockExpr$1$$anonfun$apply$49.apply(ScalametaParser.scala:2085)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$blockExpr$1$$anonfun$apply$49.apply(ScalametaParser.scala:2084)
  scala.meta.internal.parsers.ScalametaParser.inBraces(ScalametaParser.scala:338)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$blockExpr$1.apply(ScalametaParser.scala:2083)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$blockExpr$1.apply(ScalametaParser.scala:2083)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser.blockExpr(ScalametaParser.scala:2082)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$simpleExpr$1.apply(ScalametaParser.scala:1965)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$simpleExpr$1.apply(ScalametaParser.scala:1943)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser.simpleExpr(ScalametaParser.scala:1943)
  scala.meta.internal.parsers.ScalametaParser.prefixExpr(ScalametaParser.scala:1921)
  scala.meta.internal.parsers.ScalametaParser.postfixExpr(ScalametaParser.scala:1897)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1$$anonfun$41.apply(ScalametaParser.scala:1594)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1$$anonfun$41.apply(ScalametaParser.scala:1594)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
  scala.meta.internal.parsers.ScalametaParser.autoPos(ScalametaParser.scala:400)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1.apply(ScalametaParser.scala:1594)
  scala.meta.internal.parsers.ScalametaParser$$anonfun$expr$1.apply(ScalametaParser.scala:1522)
  scala.meta.internal.parsers.ScalametaParser.atPos(ScalametaParser.scala:394)
...
```

### PR DESCRIPTION
**Pull request by poslegm**
Hello!

This is my first contribution here and I might be wrong with suite for tests, naming convention and other stuff.

Fixes #492 

And this is a source of https://github.com/scalameta/scalafmt/issues/1245

### CODE REVIEW

**Comment by poslegm** [comment]
@olafurpg @gabro @ckipp01 is there way to test scalameta regressions on a large codebase? (like [scala-repos](https://github.com/olafurpg/scala-repos) formatting for scalafmt)

**Comment by olafurpg** [comment]
Ignoring the unrelated failure in CLA. If you haven't signed the CLA, can you please complete https://www.lightbend.com/contribute/cla ?


> is there way to test scalameta regressions on a large codebase?

There is in testkit, here is one example test case that I believe parses the same corpus as scala-repos https://github.com/scalameta/scalameta/blob/a4f858c50b46218679292cabc6c41ea3b407105f/scalameta/testkit/src/test/scala/scala/meta/tests/contrib/ScaladocParserProps.scala#L14

**Comment by poslegm** [comment]
CLA signed, there is green CLA check: https://github.com/scalameta/scalameta/runs/483638616

Red job isn't actual.

**Comment by olafurpg** [comment]
FYI, this fix is included in v4.3.4 that just completed releasing

**Comment by kitbellew** [comment]
@poslegm @olafurpg for some reason, the version of `org.scalameta:testkit:4.3.4` downloaded on my mac by coursier doesn't contain the `scala.meta.testkit.DiffAssertions` class, so my local `scalafmt` tests fail. any ideas?

**Comment by olafurpg** [comment]
@kitbellew looks like this file got removed after the migration to MUnit (https://github.com/scalameta/scalameta/pull/1957).

Testkit in general has not followed the same stability guarantees as the main Scalameta modules. We could add the following stub to fill in the missing trait

```scala
package scala.meta.testkit

import munit.internal.Diffs
import munit.Location

trait DiffAssertions {

  @deprecated("Use assertNoDiff instead", "4.3.5")
  def assertNoDiffOrPrintExpected(obtained: String, expected: String, title: String = "")(implicit loc: Location): Boolean = {
    Diffs.assertNoDiff(obtained, expected, title)
  }

  def assertNoDiff(obtained: String, expected: String, title: String = "")(implicit loc: Location): Boolean = {
    Diffs.assertNoDiff(obtained, expected, title)
  }

}
```

It's not a drop-in replacement since the location of the call-site is tracked with `munit.Location` instead of `org.scalatest.Position`.

Can you try to copy-paste that into the Scalafmt test suite and see if it works? If so, we might recommend people to do that instead of cut a new testkit release with this file. Alternatively, I'm open to add this file back

**Comment by olafurpg** [comment]
EDIT: I updated the code example so that it compiles

**Comment by poslegm** [comment]
Yes, I found the problem in the `DynamicSuite`. It's bad that scalafmt CI is green. On CI we run only `tests/test` but other modules don't checked.

@olafurpg why `ci-test` [command](https://github.com/scalameta/scalafmt/blob/master/build.sbt#L51-L63) doesn't run _all_ tests?

**Comment by olafurpg** [comment]
We should update ci-test to run all tests but note that we don't want to run `sbt test`. It might not be as bad now as it was before (when we had ~107 publishable modules in this build) and doing `sbt test` was ~2x slower than `sbt tests/test` even if it ran the same amount of tests

**Pull request merged**
