### PR TITLE
Fix vanish unicode escape in string interpolation

### PR DESCRIPTION
**Pull request by avdv**
This fixes a problem where unicode escape sequences are removed from interpolated string literals.

See #819. 

Where should I add a test case?

### CODE REVIEW

**Comment by avdv** [comment]
> Thank you for this contribution @avdv All the tests still pass, which is a good sign 😄 Can you please sign the Scala CLA? See link on travis.

Sure, I already did in the meantime.
> I took a stab at testing this fix in scalameta/scalameta/compare/master...olafurpg:fix-unicode-escape-vanish?expand=1 but couldn't get it to work. I think we need to write the input in an external file in order to preserve the unicode escapes.

Oh, yes. That's a problem.
> Can you try to reproduce the bug?

I'll look into it.

**Comment by avdv** [comment]
Hi @olafurpg,

your test case seems to work just fine for me: 🎉 
```
[info] - s"${x}\uef17" *** FAILED ***
[info]   ===========
[info]   => Obtained
[info]   ===========
[info]   s"${x}7"
[info]   
[info]   =======
[info]   => Diff
[info]   =======
[info]   -s"${x}7"
[info]   +s"${x}\uef17" (BaseTokenizerSuite.scala:22)
[info] - s"]2;SBT${titleName}${titleBranch}\u0007" *** FAILED ***
[info]   ===========
[info]   => Obtained
[info]   ===========
[info]   s"]2;SBT${titleName}${titleBranch}7"
[info]   
[info]   =======
[info]   => Diff
[info]   =======
[info]   -s"]2;SBT${titleName}${titleBranch}7"
[info]   +s"]2;SBT${titleName}${titleBranch}\u0007" (BaseTokenizerSuite.scala:22)
```
(after commenting my additional lines)

**Comment by olafurpg** [comment]
Whoop whoop, CI is happy 🎉

**Comment by avdv** [comment]
Thanks, @olafurpg for actually doing the heavy lifting here... !! 👍

**Comment by olafurpg** [comment]
Thank you for digging into LegacyScanner! It's a place I avoid as I can, testing is easy 😄

**Pull request merged**
