### PR TITLE
WIP Adapt to proposed changes to Typer in 2.12.7

### PR DESCRIPTION
**Pull request by retronym**
Working towards support of:

https://github.com/scala/scala/pull/7147

Locally:

```
$ cd /code/scala && git log -1 && git diff head
commit da58d8e4f13c75f9ac757ef6f78d40b9cd885c15 (HEAD -> perf-backport/omnibus-first-pr, retronym/perf-backport/omnibus-first-pr, origin/pr/7147)
Merge: 0a8e00cb18 8e4a40a688
Author: Jason Zaugg <jzaugg@gmail.com>
Date:   Fri Sep 14 16:20:05 2018 +1000

    Merge remote-tracking branch 'origin/2.12.x' into perf-backport/omnibus-first-pr
diff --git a/src/compiler/scala/tools/nsc/Global.scala b/src/compiler/scala/tools/nsc/Global.scala
index 42b8157508..d43564e44e 100644
--- a/src/compiler/scala/tools/nsc/Global.scala
+++ b/src/compiler/scala/tools/nsc/Global.scala
@@ -1142,7 +1142,7 @@ class Global(var currentSettings: Settings, reporter0: Reporter)
     val compiledFiles   = new mutable.HashSet[String]

     /** A map from compiled top-level symbols to their source files */
-    val symSource = new mutable.AnyRefMap[Symbol, AbstractFile]
+    val symSource = new mutable.HashMap[Symbol, AbstractFile]

     /** A map from compiled top-level symbols to their picklers */
     val symData = new mutable.AnyRefMap[Symbol, PickleBuffer]

$ sbt clean setupPublishCore dist/mkPack
```

```
$ cd /code/scalameta

$ sbt clean "++ 2.12.6=/code/scala/build/pack" testsJVM/test
[info] Loading global plugins from /Users/jz/.sbt/0.13/plugins
[info] Loading project definition from /Users/jz/code/scalameta/project/project
[info] Loading project definition from /Users/jz/code/scalameta/project
[info] Resolving key references (50441 settings) ...
[info] Welcome to scalameta 4.0.0-RC1-4-4a0d996c
[info] Set current project to scalametaRoot (in build file:/Users/jz/code/scalameta/)
[success] Total time: 0 s, completed 18/09/2018 2:34:50 PM
[info] Setting Scala home to /code/scala/build/pack with actual version 2.12.7-20180914-062005-da58d8e
[info] 	and using 2.12.6 for resolving dependencies.
[info] Reapplying settings...
[info] Welcome to scalameta 4.0.0-RC1-4-4a0d996c
[info] Set current project to scalametaRoot (in build file:/Users/jz/code/scalameta/)
[info] Compiling 2 protobuf files to /Users/jz/code/scalameta/semanticdb/semanticdb/.jvm/target/scala-2.12/src_managed/main
[info] Compiling schema /Users/jz/code/scalameta/semanticdb/semanticdb/semanticdb.proto
[info] Compiling schema /Users/jz/code/scalameta/semanticdb/semanticdb/semanticidx.proto
protoc-jar: protoc version: 3.5.1, detected platform: osx-x86_64 (mac os x/x86_64)
protoc-jar: embedded: bin/3.5.1/protoc-3.5.1-osx-x86_64.exe
protoc-jar: executing: [/var/folders/b7/xcc2k0ln6ldcv247ffpy2d1w0000gp/T/protocjar5116797196086050102/bin/protoc.exe, --plugin=protoc-gen-scala=/var/folders/b7/xcc2k0ln6ldcv247ffpy2d1w0000gp/T/protocbridge6314743011019068371, --scala_out=flat_package,grpc:/Users/jz/code/scalameta/semanticdb/semanticdb/.jvm/target/scala-2.12/src_managed/main, -I/Users/jz/code/scalameta/semanticdb/semanticdb, -I/Users/jz/code/scalameta/semanticdb/semanticdb/.jvm/target/protobuf_external, -I/Users/jz/code/scalameta/semanticdb/semanticdb, -I/Users/jz/code/scalameta/semanticdb/semanticdb/.jvm/target/protobuf_external, /Users/jz/code/scalameta/semanticdb/semanticdb/semanticdb.proto, /Users/jz/code/scalameta/semanticdb/semanticdb/semanticidx.proto]
[info] Compiling 4 Scala sources to /Users/jz/code/scalameta/semanticdb/cli/.jvm/target/scala-2.12/classes...
[info] Compiling 1 Scala source to /Users/jz/code/scalameta/semanticdb/integration-macros/target/scala-2.12/classes...
[info] Compiling protobuf
[info] Protoc target directory: /Users/jz/code/scalameta/semanticdb/semanticdb/.jvm/target/scala-2.12/src_managed/main
[info] Compiling 26 Scala sources to /Users/jz/code/scalameta/semanticdb/semanticdb/.jvm/target/scala-2.12/classes...
[info] Compiling 55 Scala sources to /Users/jz/code/scalameta/scalameta/common/jvm/target/scala-2.12/classes...
[info] Compiling 3 Scala sources to /Users/jz/code/scalameta/scalameta/dialects/jvm/target/scala-2.12/classes...
[info] Compiling 13 Scala sources to /Users/jz/code/scalameta/scalameta/io/jvm/target/scala-2.12/classes...
[info] Compiling 4 Scala sources to /Users/jz/code/scalameta/semanticdb/metai/target/scala-2.12/classes...
[info] Compiling 6 Scala sources to /Users/jz/code/scalameta/scalameta/inputs/jvm/target/scala-2.12/classes...
[info] Compiling 6 Scala sources to /Users/jz/code/scalameta/semanticdb/javac/target/scala-2.12/classes...
[info] Compiling 37 Scala sources to /Users/jz/code/scalameta/semanticdb/metacp/target/scala-2.12/classes...
[info] Compiling 13 Scala sources to /Users/jz/code/scalameta/scalameta/tokens/jvm/target/scala-2.12/classes...
[info] Compiling 13 Scala sources to /Users/jz/code/scalameta/semanticdb/metap/.jvm/target/scala-2.12/classes...
[info] Packaging /Users/jz/code/scalameta/semanticdb/javac/target/scala-2.12/semanticdb-javac_2.12-4.0.0-RC1-4-4a0d996c.jar ...
[info] Done packaging.
[info] Compiling 4 Scala sources to /Users/jz/code/scalameta/semanticdb/symtab/target/scala-2.12/classes...
[info] Compiling 14 Scala sources to /Users/jz/code/scalameta/scalameta/tokenizers/jvm/target/scala-2.12/classes...
[info] Compiling 14 Scala sources to /Users/jz/code/scalameta/scalameta/trees/jvm/target/scala-2.12/classes...
[info] Compiling 4 Scala sources to /Users/jz/code/scalameta/scalameta/transversers/jvm/target/scala-2.12/classes...
[info] Compiling 9 Scala sources to /Users/jz/code/scalameta/scalameta/parsers/jvm/target/scala-2.12/classes...
[info] Compiling 6 Scala sources to /Users/jz/code/scalameta/scalameta/quasiquotes/jvm/target/scala-2.12/classes...
[info] Compiling 1 Scala source to /Users/jz/code/scalameta/scalameta/scalameta/jvm/target/scala-2.12/classes...
[info] Compiling 24 Scala sources to /Users/jz/code/scalameta/semanticdb/scalac/library/target/scala-2.12/classes...
[info] Compiling 29 Scala sources to /Users/jz/code/scalameta/scalameta/contrib/jvm/target/scala-2.12/classes...
[info] Compiling 10 Scala sources to /Users/jz/code/scalameta/scalameta/testkit/target/scala-2.12/classes...
[info] Compiling 1 Scala source to /Users/jz/code/scalameta/scalameta/interactive/target/scala-2.12/classes...
[info] Packaging /Users/jz/code/scalameta/semanticdb/scalac/plugin/target/scala-2.12/semanticdb-scalac_2.12.6-4.0.0-RC1-4-4a0d996c.jar ...
[info] Done packaging.
[info] Compiling 3 Scala sources to /Users/jz/code/scalameta/semanticdb/metac/target/scala-2.12/classes...
[info] Compiling 26 Scala sources and 25 Java sources to /Users/jz/code/scalameta/semanticdb/integration/target/scala-2.12/classes...
java.lang.AbstractMethodError: Method scala/meta/internal/semanticdb/scalac/SemanticdbPlugin.scala$tools$nsc$typechecker$Contexts$_setter_$scala$tools$nsc$typechecker$Contexts$$SomeNil_$eq(Lscala/Some;)V is abstract
	at scala.meta.internal.semanticdb.scalac.SemanticdbPlugin.scala$tools$nsc$typechecker$Contexts$_setter_$scala$tools$nsc$typechecker$Contexts$$SomeNil_$eq(SemanticdbPlugin.scala)
	at scala.tools.nsc.typechecker.Contexts.$init$(Contexts.scala:1570)
	at scala.meta.internal.semanticdb.scalac.SemanticdbPlugin.<init>(SemanticdbPlugin.scala:10)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

That indicates that `SemanticdbPlugin` wasn't actually compiled against the new `Analyzer`, otherwise it ought to have the trait setter to initialized: [`SomeNil`](https://github.com/retronym/scala/blob/a857be2e121607ae9609c8c6f5578f709d98e498/src/compiler/scala/tools/nsc/typechecker/Contexts.scala#L1570)

### CODE REVIEW

**Comment by retronym** [comment]
I made some (temporary?) changes to this repo to let it pull in a 2.12.7-bin snapshot version of Scala, but treat that as "2.12.6" with respect to looking up macro-paradise, and "2.12.7' when picking the compiler-version-conditional source folder.

I had to revert/tweak a few things in the scala/scala PR, but with those:

```
$ sbt clean "++ 2.12.7-bin-036143b-SNAPSHOT" testsJVM/test

[info] Passed: Total 1977, Failed 0, Errors 0, Passed 1977, Ignored 2
[success] Total time: 142 s, completed 18/09/2018 4:23:00 PM
```

**Comment by olafurpg** [comment]
Thank you @retronym for opening this PR. Is this a blocker for 2.1.7? I thought the SemanticDB compiler plugin was excluded from the community build. It is not the intention to block scala/scala PRs touching typers.

Normally, we upgrade after a stable Scala version is out. I agree the deep coupling is undesirable and I would love to discuss ways to upstream the instrumentation from the `// scalac deviation` comments.

**Comment by retronym** [comment]
@olafurpg Looks like [it is included](https://github.com/scala/community-builds/blob/2.12.x/configs/community.dbuild#L1730-L1749). It was the part that failed in https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3528/consoleText.

I'm glad we found the incompatibility, because some of the changes I made would have been hard to adapt to.

Having `scalameta` failing in the community build seems to knock out quite a few projects transitively:

```
[info] --== Console Notifications ==--
[info] ---==  Execution Report ==---
[info] Report from the dbuild run for dbuild: 
[info] Project acyclic---------------------: SUCCESS (project rebuilt ok)
[info] Project akka-actor------------------: SUCCESS (project rebuilt ok)
[info] Project akka-contrib-extra----------: DID NOT RUN (stuck on broken dependencies: akka-more)
[info] Project akka-http-------------------: SUCCESS (project rebuilt ok)
[info] Project akka-http-cors--------------: SUCCESS (project rebuilt ok)
[info] Project akka-http-json--------------: SUCCESS (project rebuilt ok)
[info] Project akka-http-session-----------: SUCCESS (project rebuilt ok)
[info] Project akka-more-------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project akka-persistence-cassandra--: DID NOT RUN (stuck on broken dependencies: akka-more)
[info] Project akka-persistence-jdbc-------: DID NOT RUN (stuck on broken dependencies: akka-more)
[info] Project akka-stream-----------------: SUCCESS (project rebuilt ok)
[info] Project algebra---------------------: SUCCESS (project rebuilt ok)
[info] Project argonaut--------------------: SUCCESS (project rebuilt ok)
[info] Project argonaut-shapeless----------: SUCCESS (project rebuilt ok)
[info] Project atto------------------------: SUCCESS (project rebuilt ok)
[info] Project autowire--------------------: SUCCESS (project rebuilt ok)
[info] Project base64----------------------: SUCCESS (project rebuilt ok)
[info] Project better-files----------------: SUCCESS (project rebuilt ok)
[info] Project better-monadic-for----------: SUCCESS (project rebuilt ok)
[info] Project blaze-----------------------: SUCCESS (project rebuilt ok)
[info] Project boopickle-------------------: SUCCESS (project rebuilt ok)
[info] Project breeze----------------------: SUCCESS (project rebuilt ok)
[info] Project cachecontrol----------------: SUCCESS (project rebuilt ok)
[info] Project case-app--------------------: SUCCESS (project rebuilt ok)
[info] Project catalysts-------------------: SUCCESS (project rebuilt ok)
[info] Project cats------------------------: SUCCESS (project rebuilt ok)
[info] Project cats-effect-----------------: SUCCESS (project rebuilt ok)
[info] Project circe-----------------------: SUCCESS (project rebuilt ok)
[info] Project circe-config----------------: SUCCESS (project rebuilt ok)
[info] Project circe-derivation------------: SUCCESS (project rebuilt ok)
[info] Project classpath-shrinker----------: SUCCESS (project rebuilt ok)
[info] Project classutil-------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project cloc-plugin-----------------: SUCCESS (project rebuilt ok)
[info] Project conductr-lib----------------: DID NOT RUN (stuck on broken dependencies: akka-more)
[info] Project coursier--------------------: SUCCESS (project rebuilt ok)
[info] Project coursier-small--------------: SUCCESS (project rebuilt ok)
[info] Project curryhoward-----------------: SUCCESS (project rebuilt ok)
[info] Project discipline------------------: SUCCESS (project rebuilt ok)
[info] Project dispatch--------------------: SUCCESS (project rebuilt ok)
[info] Project doodle----------------------: SUCCESS (project rebuilt ok)
[info] Project eff-------------------------: SUCCESS (project rebuilt ok)
[info] Project elastic4s-------------------: SUCCESS (project rebuilt ok)
[info] Project enumeratum------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project euler-----------------------: SUCCESS (project rebuilt ok)
[info] Project expecty---------------------: SUCCESS (project rebuilt ok)
[info] Project export-hook-----------------: SUCCESS (project rebuilt ok)
[info] Project fansi-----------------------: SUCCESS (project rebuilt ok)
[info] Project fast-string-interpolator----: SUCCESS (project rebuilt ok)
[info] Project fastparse-------------------: SUCCESS (project rebuilt ok)
[info] Project fs2-------------------------: SUCCESS (project rebuilt ok)
[info] Project fs2-reactive-streams--------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project genjavadoc------------------: SUCCESS (project rebuilt ok)
[info] Project geny------------------------: SUCCESS (project rebuilt ok)
[info] Project gigahorse-------------------: SUCCESS (project rebuilt ok)
[info] Project giter8----------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project github4s--------------------: SUCCESS (project rebuilt ok)
[info] Project grizzled--------------------: SUCCESS (project rebuilt ok)
[info] Project http4s----------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project http4s-parboiled2-----------: SUCCESS (project rebuilt ok)
[info] Project http4s-websocket------------: SUCCESS (project rebuilt ok)
[info] Project jackson-module-scala--------: SUCCESS (project rebuilt ok)
[info] Project jawn-0-10-------------------: SUCCESS (project rebuilt ok)
[info] Project jawn-0-11-------------------: SUCCESS (project rebuilt ok)
[info] Project jawn-fs2--------------------: SUCCESS (project rebuilt ok)
[info] Project json4s----------------------: SUCCESS (project rebuilt ok)
[info] Project jsoniter-scala--------------: SUCCESS (project rebuilt ok)
[info] Project kind-projector--------------: SUCCESS (project rebuilt ok)
[info] Project kittens---------------------: SUCCESS (project rebuilt ok)
[info] Project kxbmap-configs--------------: SUCCESS (project rebuilt ok)
[info] Project lagom-----------------------: DID NOT RUN (stuck on broken dependencies: akka-more)
[info] Project lift-json-------------------: SUCCESS (project rebuilt ok)
[info] Project lightbend-emoji-------------: SUCCESS (project rebuilt ok)
[info] Project linter----------------------: SUCCESS (project rebuilt ok)
[info] Project log4s-----------------------: SUCCESS (project rebuilt ok)
[info] Project machinist-------------------: SUCCESS (project rebuilt ok)
[info] Project macro-compat----------------: SUCCESS (project rebuilt ok)
[info] Project macro-paradise--------------: SUCCESS (project rebuilt ok)
[info] Project magnolia--------------------: SUCCESS (project rebuilt ok)
[info] Project mercator--------------------: SUCCESS (project rebuilt ok)
[info] Project metaconfig------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project metrics-scala---------------: SUCCESS (project rebuilt ok)
[info] Project mima------------------------: SUCCESS (project rebuilt ok)
[info] Project minitest--------------------: SUCCESS (project rebuilt ok)
[info] Project monix-----------------------: SUCCESS (project rebuilt ok)
[info] Project monocle---------------------: SUCCESS (project rebuilt ok)
[info] Project mouse-----------------------: SUCCESS (project rebuilt ok)
[info] Project multibot--------------------: SUCCESS (project rebuilt ok)
[info] Project nscala-time-----------------: SUCCESS (project rebuilt ok)
[info] Project nyaya-----------------------: SUCCESS (project rebuilt ok)
[info] Project paiges----------------------: SUCCESS (project rebuilt ok)
[info] Project paradox---------------------: SUCCESS (project rebuilt ok)
[info] Project parboiled-------------------: SUCCESS (project rebuilt ok)
[info] Project parboiled2------------------: SUCCESS (project rebuilt ok)
[info] Project pascal----------------------: SUCCESS (project rebuilt ok)
[info] Project pcplod----------------------: SUCCESS (project rebuilt ok)
[info] Project perfolation-----------------: SUCCESS (project rebuilt ok)
[info] Project play-core-------------------: DID NOT RUN (stuck on broken dependencies: akka-more)
[info] Project play-doc--------------------: SUCCESS (project rebuilt ok)
[info] Project play-json-------------------: SUCCESS (project rebuilt ok)
[info] Project play-webgoat----------------: DID NOT RUN (stuck on broken dependencies: akka-more)
[info] Project play-ws---------------------: SUCCESS (project rebuilt ok)
[info] Project portable-scala-reflect------: SUCCESS (project rebuilt ok)
[info] Project pprint----------------------: SUCCESS (project rebuilt ok)
[info] Project pureconfig------------------: DID NOT RUN (stuck on broken dependencies: enumeratum)
[info] Project refined---------------------: DID NOT RUN (stuck on broken dependencies: enumeratum)
[info] Project sbinary---------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project sbt-------------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project sbt-io----------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project sbt-librarymanagement-------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project sbt-testng------------------: SUCCESS (project rebuilt ok)
[info] Project sbt-util--------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project scala-----------------------: SUCCESS (project rebuilt ok)
[info] Project scala-async-----------------: SUCCESS (project rebuilt ok)
[info] Project scala-collection-compat-----: SUCCESS (project rebuilt ok)
[info] Project scala-collections-laws------: SUCCESS (project rebuilt ok)
[info] Project scala-continuations---------: SUCCESS (project rebuilt ok)
[info] Project scala-debugger--------------: FAILED (RuntimeException: )
[info] Project scala-gopher----------------: SUCCESS (project rebuilt ok)
[info] Project scala-java8-compat----------: SUCCESS (project rebuilt ok)
[info] Project scala-js--------------------: SUCCESS (project rebuilt ok)
[info] Project scala-js-stubs--------------: SUCCESS (project rebuilt ok)
[info] Project scala-logging---------------: SUCCESS (project rebuilt ok)
[info] Project scala-newtype---------------: SUCCESS (project rebuilt ok)
[info] Project scala-parser-combinators----: SUCCESS (project rebuilt ok)
[info] Project scala-partest---------------: SUCCESS (project rebuilt ok)
[info] Project scala-records---------------: SUCCESS (project rebuilt ok)
[info] Project scala-refactoring-----------: SUCCESS (project rebuilt ok)
[info] Project scala-sculpt----------------: SUCCESS (project rebuilt ok)
[info] Project scala-ssh-------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project scala-stm-------------------: SUCCESS (project rebuilt ok)
[info] Project scala-swing-----------------: SUCCESS (project rebuilt ok)
[info] Project scala-xml-quote-------------: SUCCESS (project rebuilt ok)
[info] Project scalacheck------------------: SUCCESS (project rebuilt ok)
[info] Project scalacheck-shapeless--------: SUCCESS (project rebuilt ok)
[info] Project scalachess------------------: SUCCESS (project rebuilt ok)
[info] Project scaladex--------------------: DID NOT RUN (stuck on broken dependencies: akka-more)
[info] Project scalafix--------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project scalafmt--------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project scalaj-http-----------------: SUCCESS (project rebuilt ok)
[info] Project scalajson-------------------: SUCCESS (project rebuilt ok)
[info] Project scalalib--------------------: SUCCESS (project rebuilt ok)
[info] Project scalameta-------------------: FAILED (RuntimeException: )
[info] Project scalamock-------------------: SUCCESS (project rebuilt ok)
[info] Project scalapb---------------------: SUCCESS (project rebuilt ok)
[info] Project scalaprops------------------: SUCCESS (project rebuilt ok)
[info] Project scalariform-----------------: SUCCESS (project rebuilt ok)
[info] Project scalasti--------------------: DID NOT RUN (stuck on broken dependencies: classutil)
[info] Project scalastyle------------------: SUCCESS (project rebuilt ok)
[info] Project scalatags-------------------: SUCCESS (project rebuilt ok)
[info] Project scalatest-------------------: SUCCESS (project rebuilt ok)
[info] Project scalatest-tests-------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project scalatex--------------------: SUCCESS (project rebuilt ok)
[info] Project scalaz----------------------: SUCCESS (project rebuilt ok)
[info] Project scalaz8---------------------: SUCCESS (project rebuilt ok)
[info] Project scalikejdbc-----------------: SUCCESS (project rebuilt ok)
[info] Project scallop---------------------: SUCCESS (project rebuilt ok)
[info] Project scapegoat-------------------: SUCCESS (project rebuilt ok)
[info] Project scodec----------------------: SUCCESS (project rebuilt ok)
[info] Project scodec-bits-----------------: SUCCESS (project rebuilt ok)
[info] Project scopt-----------------------: SUCCESS (project rebuilt ok)
[info] Project scoverage-------------------: SUCCESS (project rebuilt ok)
[info] Project scribe----------------------: FAILED (RuntimeException: Tests unsuccessful)
[info] Project scrooge---------------------: SUCCESS (project rebuilt ok)
[info] Project scrooge-shapes--------------: SUCCESS (project rebuilt ok)
[info] Project shaded-scalajson------------: SUCCESS (project rebuilt ok)
[info] Project shapeless-------------------: SUCCESS (project rebuilt ok)
[info] Project silencer--------------------: SUCCESS (project rebuilt ok)
[info] Project simulacrum------------------: SUCCESS (project rebuilt ok)
[info] Project singleton-ops---------------: SUCCESS (project rebuilt ok)
[info] Project sjson-new-------------------: SUCCESS (project rebuilt ok)
[info] Project sksamuel-exts---------------: SUCCESS (project rebuilt ok)
[info] Project slick-----------------------: SUCCESS (project rebuilt ok)
[info] Project sourcecode------------------: SUCCESS (project rebuilt ok)
[info] Project specs2----------------------: SUCCESS (project rebuilt ok)
[info] Project specs2-more-----------------: SUCCESS (project rebuilt ok)
[info] Project spire-----------------------: SUCCESS (project rebuilt ok)
[info] Project spray-json------------------: SUCCESS (project rebuilt ok)
[info] Project ssl-config------------------: SUCCESS (project rebuilt ok)
[info] Project sttp------------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] Project tut-------------------------: SUCCESS (project rebuilt ok)
[info] Project twirl-----------------------: SUCCESS (project rebuilt ok)
[info] Project twitter-util----------------: SUCCESS (project rebuilt ok)
[info] Project twotails--------------------: SUCCESS (project rebuilt ok)
[info] Project unfiltered------------------: SUCCESS (project rebuilt ok)
[info] Project upickle---------------------: SUCCESS (project rebuilt ok)
[info] Project utest-----------------------: SUCCESS (project rebuilt ok)
[info] Project wartremover-----------------: SUCCESS (project rebuilt ok)
[info] Project zinc------------------------: DID NOT RUN (stuck on broken dependencies: scalameta)
[info] >>> The dbuild result is----------------: FAILED (failed: scalatest-tests, scalameta, scala-debugger, akka-more, scribe, classutil, enumeratum)
```

I should be able to take make a branch like this one that edits the `2.12.6/.../*Analyzer.scala` in place, and refer to this in a fork of the community build, to unblock those projects. @SethTisue is our community  build guru so might have further insights.

**Comment by SethTisue** [comment]
> I should be able to take make a branch like this one that edits the `2.12.6/.../*Analyzer.scala` in place, and refer to this in a fork of the community build, to unblock those projects.

yes, this is exactly what I'd recommend.

and given that the coupling (in the form of copy-and-paste) between typer and Scalameta exists, it's very good to have the community build telling us early when the two become out of alignment. waiting until after 2.12.7 is released to sort it out would probably usually work, but it's risky. sorting it out in advance seems like the safer course

**Comment by retronym** [comment]
@olafurpg We're now using this PR in the  Scala community build, which is green: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3538/

I'll close this PR to leave this branch unchanged, and I suggest that you resubmit it without 240b36a as a new PR when 2.12.7 is released.

**Comment by olafurpg** [comment]
This PR has been merged into master now via #1784 and semanticdb-scalac has been released for 2.12.7. Thank you @retronym for helping us upgrade.

Would you guys be interested to discuss options for how avoid the hijacked semanticdb typer altogether? I would love to get rid of it. We would need to upstream a few attachments where there are `//+scala deviation` comments in [SemanticdbAnalyzer.scala](https://github.com/scalameta/scalameta/blob/0855a8defcefe0cec2bef80f79d43b2f974cdf9d/semanticdb/scalac/library/src/main/scala-2.12.7/scala/meta/internal/semanticdb/scalac/SemanticdbAnalyzer.scala#L26-L28). I understand care would need to be taken to avoid performance regressions and ensure the attachments are cleaned up.

**Comment by olafurpg** [comment]
FYI @retronym we have removed typer instrumentation altogether https://github.com/scalameta/scalameta/pull/1804 this should make future compiler upgrades easier at the cost of a minor regression functionality-wise.

**Pull request closed without merging**
