### PR TITLE
bump sbt 1.4.3

### PR DESCRIPTION
**Pull request by kpbochenek**
Supersedes: https://github.com/scalameta/scalameta/pull/2149

This will work? :crossed_fingers:

### CODE REVIEW

**Comment by tgodzik** [comment]
Seems there is an issue when compiling under 2.11.12 :/

I meant to report it, but haven't had the time.

**Comment by kpbochenek** [comment]
Created issue in sbt, we have to start somewhere https://github.com/sbt/sbt/issues/6124

**Comment by adpi2** [comment]
Surely something has changed in sbt causing this bug.

But I have found that there is 2 `SkipWindows` symbols defined in the same package:
- one `SkipWindows` object [here](https://github.com/scalameta/scalameta/blob/b286cdbdc4bca88bc81932efd29ef70c6f87f289/tests/jvm/src/main/scala/scala/meta/tests/SkipWindows.scala#L5)
- one `SkipWindows` val [here](https://github.com/scalameta/scalameta/blob/b286cdbdc4bca88bc81932efd29ef70c6f87f289/tests/jvm/src/test/scala/scala/meta/tests/package.scala#L5)

So I guess if we remove one of those symbols it will be easier for Zinc. I'll give a try.

**Comment by adpi2** [comment]
New PR #2185

**Pull request closed without merging**
