### PR TITLE
add David Dudson as a maintainer

### PR DESCRIPTION
**Pull request by xeno-by**
@DavidDudson has been very a active community member for quite a while.
He has contributed to a lot of valuable discussions on Gitter,
project issue trackers and pull requests. We are honored to work with David!

Thanks a bunch, @DavidDudson. Please give a 👍 if you'd like
to be added as a maintainer.

### CODE REVIEW

**Comment by DavidDudson** [comment]
:+1:

**Comment by olafurpg** [comment]
You should have merge rights so feel free to merge this PR :D

**Comment by DavidDudson** [comment]
@olafurpg I dont think @xeno-by has added as a member to github yet. Just created the PR. He was probably waiting for me to :+1:

**Comment by olafurpg** [comment]
I added you as a collaborator for time being so you should be able to merge now :)

**Comment by DavidDudson** [comment]
@olafurpg Still cant, **"Only those with write access to this repository can merge pull requests."**

**Comment by olafurpg** [comment]
Did you accept the invitation via email?

**Comment by DavidDudson** [comment]
yes

**Pull request merged**
