### PR TITLE
ScannerTokens: handle `case` after `= <indent>`

### PR DESCRIPTION
**Pull request by kitbellew**

### CODE REVIEW

**Comment by kitbellew** [comment]
MIMA failure should be fixed in #3248.

**Comment by kitbellew** [comment]
> MIMA failure should be fixed in #3248.

@tgodzik not sure if you have ideas. it seems that `sbt mima` runs on jars which are before shading. if that's true, how would we change that?

**Comment by kitbellew** [comment]
@tgodzik with this change, here's where case clause is recognized: 
- explicitly: after catch/match and indent/brace
- implicitly (as partial function):
  - after colon/equals and indent
  - inside left brace region except template and for

are there any other cases?

**Review by tgodzik — APPROVED** [review]
I can't think of another case, I guess it will show up with a bug report if there is anything.

As for shadowing vs mima, I am not sure how exactly to do it, but we would probably have to point `mimaCurrentClassfiles` at the locally published jar. We could probably run `publishLocal` first and then we would probably be able to point to that jar that was published

**Pull request merged**
