### PR TITLE
merging example code from github.com/scalameta/example

### PR DESCRIPTION
**Pull request by MasseGuillaume**
```scala
scala.meta.internal.hosts.scalac.converters.ConvertException: unexpected tree during scala.reflect -> scala.meta conversion:
ModuleDef(Modifiers(),
  org.example.Hello,
  Template(List(Select(Ident(scala), TypeName("AnyRef"))),
  noSelfType, List(DefDef(Modifiers(), termNames.CONSTRUCTOR, List(), List(List()),
  TypeTree(), Block(List(Apply(Select(Super(This(TypeName("Hello")), typeNames.EMPTY), termNames.CONSTRUCTOR),
  List())), Literal(Constant(())))), DefDef(Modifiers(), TermName("v"), List(), List(), TypeTree(), Literal(Constant(42))))))
(PackageDef) package org.example {   object Hello extends scala.AnyRef { ...
```
Is this missing `ModuleDef` ? https://github.com/scalameta/scalameta/blob/8ebdeca7b5f5259e450a29b3588c588d700cf4f7/scalahost/src/main/scala/scala/meta/internal/hosts/scalac/converters/ToMtree.scala#L38

### CODE REVIEW

**Comment by xeno-by** [comment]
Yes, the converter is far from having feature-parity with the old one.

Also, I think that it'd make sense to have examples in a separate repository so that it's possible to bind them to a stable release (e.g. to 0.0.3 that I'm about to publish right now), and then evolve them independently of what's going on in scala.meta's SNAPSHOT. Wdyt?

**Comment by xeno-by** [comment]
Btw, tomorrow (and maybe the day after tomorrow) during my preparation for the Monday's workshop at Scala World, I'll be recreating the example repo with several realistic and up-to-date examples of using scala.meta. Do you maybe have any suggestions of what I could do there?

**Comment by MasseGuillaume** [comment]
yep it can be a separate project. we can use git subtree merge to copy the source to the other repo. The advantage of having it here is to know as fast as possible when things break.

**Comment by MasseGuillaume** [comment]
For Scala World you could do a project explorer
```
org.scalameta
├── (O) Conversions
├── (O) Exceptions
├── interactive
│   ├── (C) Api
│   └── (C) Context
├── internal
│   ├── ast
│   │   ├── (O) Exceptions
│   │   ├── (C) MergeTrees
│   │   └── package
│   ├── equality
│   │   ├── (C) Helpers
│   │   ├── (C) Normalizing
│   │   ├── (PO) package
│   │   ├── (C) Semantic
│   │   └── (C) Typechecking
// ...
```
https://github.com/metadoc/metadoc/tree/develop/compilerPlugin/src/main/scala/com.scalakata.metadoc.plugin

**Comment by xeno-by** [comment]
Here's the tutorial that I've been preparing for scala.world: https://github.com/scalameta/tutorial. Since it has such a peculiar structure (multiple branches = multiple guides) and a binding to the latest stable version of scala.meta (0.4.0), I don't see how we can merge it into this repo. Maybe we could keep it separate and organize a nightly build instead?

**Comment by xeno-by** [comment]
@MasseGuillaume ping

**Comment by MasseGuillaume** [comment]
@xeno-by make sense. In this case we just need better code coverage for the tree converter.

**Pull request closed without merging**
