### PR TITLE
 Factor out the SemanticDB schema into a separate project

### PR DESCRIPTION
**Pull request by xeno-by**
In preparation for https://github.com/scalameta/scalameta/pull/1220, factor out the SemanticDB v2 schema into a separate project. No changes are applied to code - the schema remains unchanged, the package remains the same.

### CODE REVIEW

**Comment by xeno-by** [comment]
Factoring out the schema into a separate project will enable multiple follow-up actions:
  * Upstreaming https://github.com/scalameta/scalameta/pull/1174
  * Upstreaming another SemanticDB CLI utility that we developed at Twitter
  * Migrating semanticdb-scalac to pure schema in preparation for https://github.com/scalameta/scalameta/pull/1220

@olafurpg I'd appreciate if you could review this pull request today to unblock the followups.

**Comment by xeno-by** [comment]
There seems to be an annoying difference between crossProject in `sbt-scalajs` and crossProject in `sbt-crossproject`. Let's take, for example:

```
lazy val common = crossProject(JSPlatform, JVMPlatform)
  .in(file("scalameta/common"))
  .settings(
    publishableSettings,
    libraryDependencies += "com.lihaoyi" %% "sourcecode" % "0.1.3",
    description := "Bag of private and public helpers used in scalameta APIs and implementations",
    enableMacros
  )
lazy val commonJVM = common.jvm
lazy val commonJS = common.js
```

Previously, when we were using `sbt-scalajs`, commonJVM was compiled to `common_2.12-version-number.jar` and commonJS was compiled to `common_sjs0.6_2.12-version-number.jar`. 

Now, with `sbt-crossproject`, it's `commonjvm_2.12-version-number.jar` and `commonjs_sjs0.6_version-number.jar`, and I can't seem to be able to find an out-of-the-box way to avoid the `jvm` and `js` prefixes. 

@olafurpg Maybe you have any idea if I'm doing anything wrong? If not, I'll continue digging tomorrow.

**Comment by olafurpg** [comment]
I asked Seb and it seems we need to create a custom "platform" for jvm with no suffix. See https://stackoverflow.com/questions/46271505/how-do-i-change-a-projects-id-in-sbt-1-0/46276523#46276523 for how to do that, we can put it under project/JvmPlatform.scala.

**Comment by xeno-by** [comment]
@olafurpg Thanks for the investigating! I think that this is not an urgent problem to solve, since we can't crosscompile everything to native anyways yet. I reverted the sbt-crossproject commit. Let's get back to this when we're ready to take on https://github.com/scalameta/scalameta/issues/772.

**Comment by xeno-by** [comment]
@olafurpg The saga continues. Now we have to convince mima that everything's alright.

```
[error] (semanticdb2JVM/*:mimaPreviousClassfiles) sbt.ResolveException: unresolved dependency: org.scalameta#semanticdb2_2.12;2.0.0: not found
[error] (semanticdb2JS/*:mimaPreviousClassfiles) sbt.ResolveException: unresolved dependency: org.scalameta#semanticdb2_2.12;2.0.0: not found
```

Do we consider introducing a new artifact a binary incompatible change?

**Comment by xeno-by** [comment]
Mima is happy. Merging.

**Comment by xeno-by** [comment]
Okay merging, this time for reals.

**Pull request merged**
