### PR TITLE
pretty printer: backquote importees when needed

### PR DESCRIPTION
**Pull request by bjaglin**
Originally reported as https://github.com/scalacenter/scalafix/issues/1337.
Fix regression introduced in https://github.com/scalameta/scalameta/pull/2239.

### CODE REVIEW

**Review by olafurpg — APPROVED** [review]
LGTM 👍 Thank you for fixing this!

**Comment by kpbochenek** [comment]
Is this testcase correct? ```assert(q"import a.`{ q }`".syntax == "import a.`{ q }`")```
Shouldn't it be ```a.{`q`}``` ?

**Comment by bjaglin** [comment]
> Is this testcase correct? `` assert(q"import a.`{ q }`".syntax == "import a.`{ q }`") ``
> Shouldn't it be `` a.{`q`} `` ?

From my understanding, it is a correct (although nasty!) identifier: https://github.com/liancheng/scalafix-organize-imports/commit/c7bb8d27e7241e9c67c28dcfa824e036562c1f19

**Review by tgodzik — APPROVED** [review]
Thanks for fixing this! LGTM!

**Pull request merged**
