### PR TITLE
Fix Incorrent unquotation of type lambda trick (#565)

### PR DESCRIPTION
**Pull request by xavier-fernandez**

### CODE REVIEW

**Comment by xavier-fernandez** [comment]
In spite the solution is working, I feel like it is a dirty hack.

I checked on the ScalametaParser and (https://github.com/scalameta/scalameta/blob/75f626d31bf93a330f0e78c1a5d9ca7d050ab3ec/scalameta/parsers/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L1133-L1136) looks like the place to check the unquotes. Any clue on how I can improve the solution?

**Comment by xeno-by** [comment]
@xavier-fernandez Have you looked into how we implement prettyprinting priorities (https://github.com/xeno-by/scalameta/blob/a3b9640e3200ae2d296f4ece79e01d0864a52700/scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala#L26)?

**Comment by xavier-fernandez** [comment]
Thank you @xeno-by, will take a look to it :)

**Comment by xavier-fernandez** [comment]
Amend done, now it works using the prettyprinting priorities :)

**Comment by xeno-by** [comment]
@xavier-fernandez Excellent! Thank you for your contribution :)

**Comment by notxcain** [comment]
Hi! I'm on `1.6.0-635` and I'm still getting this
```scala
scala> q"def foo[A]: Foo[({ type T[F[_]] = Bar[A, F] })#T, Unit] = null".show[Syntax]
res0: String = def foo[A]: Foo[{ type T[F[_]] = Bar[A, F] }#T, Unit] = null
```

**Pull request merged**
