### PR TITLE
Add bench/

### PR DESCRIPTION
**Pull request by xeno-by**
# Scalameta benchmarks

## Running benchmarks

```
bin/bench
```

## Benchmarking methodology

Benchmarks involve running `bin/bench All` on my laptop, which includes:
  * Compiling scalap with Scala 2.11
  * Compiling scalap with Scala 2.11 and semanticdb-scalac

The numbers are probably not stable enough (because laptop)
and not precise enough (because 5/10/1). However, I can rerun these benchmarks
quickly enough not to get annoyed when doing interactive development,
and that's what matters now.

## Benchmarking configurations

ScalametaBaseline corresponds to the following compiler plugin options:

```
-P:semanticdb:mode:slim
-P:semanticdb:denotations:definitions
-P:semanticdb:synthetics:none
```

Other Scalameta configurations progressively enable more and more features:
  * ScalametaFullContents enables `-P:semanticdb:mode:fat`
  * ScalametaFullDenotations further enables `-P:semanticdb:denotations:all`
  * ScalametaFullSynthetics further enables `-P:semanticdb:synthetics:all`

## Results

```
QuickScalacBaseline            1595.274 ± 15.263  ms/op
QuickScalacRangepos            1703.097 ± 25.044  ms/op  (6% overhead)
QuickScalametaBaseline         2020.256 ± 39.586  ms/op  (25% overhead)
QuickScalametaFullContents     2081.549 ± 38.977  ms/op  (30% overhead)
QuickScalametaFullDenotations  2236.738 ± 28.241  ms/op  (39% overhead)
QuickScalametaFullSynthetics   2272.054 ± 81.361  ms/op  (42% overhead)
```

### CODE REVIEW

**Comment by xeno-by** [comment]
Somehow the numbers got screwed up after a recent rebase. My latest rerun of `bin/bench All` on my laptop gives:

```
Benchmark                      Mode    Cnt Score
QuickScalacBaseline            sample  35  1544.163 ± 18.766 ms/op
QuickScalacRangepos            sample  35  1623.975 ± 25.106 ms/op
QuickScalametaBaseline         sample  15  3870.224 ± 375.329 ms/op
QuickScalametaFullContents     sample  15  3856.802 ± 352.485 ms/op
QuickScalametaFullDenotations  sample  15  4224.783 ± 387.847 ms/op
QuickScalametaFullSynthetics   sample  15  4260.294 ± 342.503 ms/op
```

Please don't merge. I'll try to see what's going.

**Comment by xeno-by** [comment]
https://github.com/scalameta/scalameta/pull/1181/commits/9d19cc34ba8fed0b03b0137c3b99e85622adbe11 pinpoints the problem. @retronym Any idea what could be going on here?

**Comment by retronym** [comment]
Thanks for the ping.

This sounds reminiscent of https://github.com/sbt/sbt/pull/2754

If I'm reading things correctly, it appears that new Global instances dynamically create a classloader for plugin classes (except for the case that the compiler classpath happens to include the plugin class), and doesn't employ any sort of caching.

A systematic way to identify these problems is to run the `-prof hs_cl` JMH profiler and ensure that classloading does not occur during the measurement phase.

Dynamic classloading has two costs. First, the dynamically loaded code itself needs to be re compiled by JIT so will run more slowly on average. Secondly, loading new subclasses of some existing type can invalidate speculative JIT optimizations. e.g. SBT was dynamically (and repeatedly) loading a subclass of `Global`.

It should be possible to add a static classloader cache into the compiler to avoid this problem. I'll track this change as https://github.com/scala/scala-dev/issues/458

**Pull request merged**
