### PR TITLE
Add support for loading the semanticdb from jars.

### LINKED ISSUE #784: Semantic DB is not loaded from inside a jar on the classpath
A `semanticdb` file located inside a jar on the classpath passed to an offline Mirror is not loaded.

### PR DESCRIPTION
**Pull request by stuhood**
Adds support for loading the semanticdb from jars on the classpath.

I haven't added a test for loading them from a jar, and that should probably happen before merging.

Fixes #784.

### CODE REVIEW

**Comment by xeno-by** [comment]
LGTM, though it would indeed be nice to have a test for this.

**Comment by stuhood** [comment]
@xeno-by : Can you recommend the best test suite to put it in? I didn't see any tests loading the db from classpaths, but perhaps I just didn't look hard enough.

**Comment by xeno-by** [comment]
Yeah, this is an undertested area. I'd create a new suite in https://github.com/scalameta/scalameta/tree/v1.7.0/scalahost/nsc/src/test/scala/scala/meta/tests/scalahost/v1.

**Comment by stuhood** [comment]
This one probably doesn't block the talk, so I'm going to let it idle until next week.

**Comment by stuhood** [comment]
I guess this has completely bitrotted at this point! Closing.

**Comment by xeno-by** [comment]
I've already ported this to the code in my megabranch :)

**Pull request closed without merging**
