### PR TITLE
Include diagnostics with offset positions

### LINKED ISSUE #1530: Unused private val warning are not reported in messages
Hi there,

We are not seeing the private val warning in the messages.

Related to: https://github.com/scalacenter/scalafix/issues/626
See: https://github.com/scalacenter/scalafix/pull/723#issuecomment-387017310

Cheers

### PR DESCRIPTION
**Pull request by lgirault**
Relax RelevantMessage condition to forward unused local warnings.

Fix #1530

### CODE REVIEW

**Comment by lgirault** [comment]
My first reflex was to add a `Position.Offset` to `Position.Range` and `Position.None` (see https://github.com/scalameta/scalameta/compare/master...lgirault:offset ) .
Is there a reason why it does not exists ?

**Comment by olafurpg** [comment]
> My first reflex was to add a Position.Offset to Position.Range and Position.None (see master...lgirault:offset ) .
> Is there a reason why it does not exists ?

A large number of bugs and pains working with positions in scala-compiler revolve around different kinds of positions. In Scalameta we try to keep the number of concepts as few as possible. Since offset positions can be treated as zero-width range positions there is no need for `Position.Offset`

**Comment by lgirault** [comment]
You're welcome ! I'm trying to get more involved in the oss ^_^

**Comment by lgirault** [comment]
and thank you for the answer!

**Comment by lgirault** [comment]
ok that's weird. I have a case of "work on my machine" :s 
I'll try to check tonight the problem

**Comment by lgirault** [comment]
thank you @joan38 
So I found the problem, the warnings are different in scala 2.11 and 2.12 but I'm not sure if the solution I used is right

**Pull request merged**
