### PR TITLE
ReificationMacros: no `dialectOnly` if use source

### LINKED ISSUE #3546: New warning under `-Wunused:locals` on main for quasiquotes expanded code
https://github.com/scalameta/scalameta/pull/3480 introduces a warning

```
//> using scala 2.13.12
//> using option -Wunused:locals

//> using repository sonatype:snapshots
//> using dep org.scalameta::scalameta:4.8.15+150-a7c0baa0-SNAPSHOT

import scala.meta._

object Quasiquotes {
  importee"importee"
}
```

```scala
$ scala-cli compile quasiquotes.scala 
Compiling project (Scala 2.13.12, JVM (17))
[warn] ./quasiquotes.scala:10:3
[warn] local val dialectOnly$macro$4 in value <local Quasiquotes> is never used
[warn]   importee"importee"
[warn]   ^
Compiled project (Scala 2.13.12, JVM (17))
```

### PR DESCRIPTION
**Pull request by kitbellew**
Follow-up to #3549. Fixes #3546.

I do not remember why I made it `implicit`, and that's the only thing that I am still not sure about; if it was important, have to keep it and, perhaps, use that gpt4 suggestion of adding `val _ = dialectOnly` to avoid unused warnings.

### CODE REVIEW

**Comment by bjaglin** [comment]
This looks good from a user perspective, I don't get any warning on macro-expanded code when building scalafix, so it fixes https://github.com/scalameta/scalameta/issues/3546 :+1: 

Can't really comment on the reification logic though.

**Review by bjaglin — APPROVED** [review]
FWIW, I see that dialects are passed explicitly in expanded code, so I am not sure the implicit has any effect?

On the snapshot I initially reported the issue:
```
$ scalac -classpath  $(cs fetch -r sonatype:snapshots org.scalameta:scalameta_2.13:4.8.15+150-a7c0baa0-SNAPSHOT | paste -sd ':' -) quasiquotes.scala -Wunused:locals -Xprint:typer
quasiquotes.scala:11: warning: local val dialectOnly$macro$4 in value <local Quasiquotes> is never used
  importee"importee"
  ^
[[syntax trees at end of                     typer]] // quasiquotes.scala
package <empty> {
  import scala.meta._;
  object Quasiquotes extends scala.AnyRef {
    def <init>(): Quasiquotes.type = {
      Quasiquotes.super.<init>();
      ()
    };
    {
      val dialect$macro$2: meta.dialects.Scala213.type = meta.this.Dialect.current;
      implicit val dialectOnly$macro$4: meta.trees.Origin.DialectOnly = new scala.meta.trees.Origin.DialectOnly(dialect$macro$2);
      val parsedSource$macro$3: meta.trees.Origin.ParsedSource = new scala.meta.trees.Origin.ParsedSource(scala.meta.inputs.Input.String.apply("importee"))(dialect$macro$2);
      scala.meta.Importee.Name.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$3, 0, 3), scala.meta.Name.Indeterminate.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$3, 1, 2), "importee")(meta.this.Dialect.current))(meta.this.Dialect.current)
    }
  }
}

1 warning
```

**Review by tgodzik — APPROVED** [review]

**Comment by kitbellew** [comment]
> FWIW, I see that dialects are passed explicitly in expanded code, so I am not sure the implicit has any effect?
> 
> On the snapshot I initially reported the issue:
> 
> ```
> $ scalac -classpath  $(cs fetch -r sonatype:snapshots org.scalameta:scalameta_2.13:4.8.15+150-a7c0baa0-SNAPSHOT | paste -sd ':' -) quasiquotes.scala -Wunused:locals -Xprint:typer
> ```

@bjaglin can i ask to run another test like this and share the results of the typer output, but this time with a different dialect? i.e. add `implicit val dialect = scala.meta.dialects.Scala213` or any other dialect (as long as it's not `meta.this.Dialect.current`).

**Comment by kitbellew** [comment]
> > FWIW, I see that dialects are passed explicitly in expanded code, so I am not sure the implicit has any effect?
> > On the snapshot I initially reported the issue:
> > ```
> > $ scalac -classpath  $(cs fetch -r sonatype:snapshots org.scalameta:scalameta_2.13:4.8.15+150-a7c0baa0-SNAPSHOT | paste -sd ':' -) quasiquotes.scala -Wunused:locals -Xprint:typer
> > ```
> 
> @bjaglin can i ask to run another test like this and share the results of the typer output, but this time with a different dialect? i.e. add `implicit val dialect = scala.meta.dialects.Scala213` or any other dialect (as long as it's not `meta.this.Dialect.current`).

or just share the contents of your `quasiquotes.scala` :) so i could try it myself.

**Comment by bjaglin** [comment]
```scala
$ cat quasiquotes.scala 
import scala.meta._
object Quasiquotes {
  {
    import scala.meta.dialects.Scala3
    importee"scala3"
  }
  {
    importee"default"
  }
}
```

### Post https://github.com/scalameta/scalameta/pull/3480
```scala
$ scalac -classpath  $(cs fetch -r sonatype:snapshots org.scalameta:scalameta_2.13:4.8.15+150-a7c0baa0-SNAPSHOT | paste -sd ':' -) quasiquotes.scala -Wunused:locals -Xprint:typer
quasiquotes.scala:5: warning: local val dialectOnly$macro$4 in value <local Quasiquotes> is never used
    importee"scala3"
    ^
quasiquotes.scala:8: warning: local val dialectOnly$macro$8 in value <local Quasiquotes> is never used
    importee"default"
    ^
[[syntax trees at end of                     typer]] // quasiquotes.scala
package <empty> {
  import scala.meta._;
  object Quasiquotes extends scala.AnyRef {
    def <init>(): Quasiquotes.type = {
      Quasiquotes.super.<init>();
      ()
    };
    {
      import scala.meta.dialects.Scala3;
      {
        val dialect$macro$2: scala.meta.Dialect = scala.meta.dialects.`package`.Scala3;
        implicit val dialectOnly$macro$4: meta.trees.Origin.DialectOnly = new scala.meta.trees.Origin.DialectOnly(dialect$macro$2);
        val parsedSource$macro$3: meta.trees.Origin.ParsedSource = new scala.meta.trees.Origin.ParsedSource(scala.meta.inputs.Input.String.apply("scala3"))(dialect$macro$2);
        scala.meta.Importee.Name.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$3, 0, 3), scala.meta.Name.Indeterminate.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$3, 1, 2), "scala3")(scala.meta.dialects.`package`.Scala3))(scala.meta.dialects.`package`.Scala3)
      }
    };
    {
      val dialect$macro$6: meta.dialects.Scala213.type = meta.this.Dialect.current;
      implicit val dialectOnly$macro$8: meta.trees.Origin.DialectOnly = new scala.meta.trees.Origin.DialectOnly(dialect$macro$6);
      val parsedSource$macro$7: meta.trees.Origin.ParsedSource = new scala.meta.trees.Origin.ParsedSource(scala.meta.inputs.Input.String.apply("default"))(dialect$macro$6);
      scala.meta.Importee.Name.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$7, 0, 3), scala.meta.Name.Indeterminate.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$7, 1, 2), "default")(meta.this.Dialect.current))(meta.this.Dialect.current)
    }
  }
}

2 warnings
```

### Post https://github.com/scalameta/scalameta/pull/3551

```scala
$ scalac -classpath $(cs fetch org.scalameta::scalameta:4.8.15-SNAPSHOT | paste -sd ':' -) quasiquotes.scala -Wunused:locals -Xprint:typer
[[syntax trees at end of                     typer]] // quasiquotes.scala
package <empty> {
  import scala.meta._;
  object Quasiquotes extends scala.AnyRef {
    def <init>(): Quasiquotes.type = {
      Quasiquotes.super.<init>();
      ()
    };
    {
      import scala.meta.dialects.Scala3;
      {
        val dialect$macro$2: scala.meta.Dialect = scala.meta.dialects.`package`.Scala3;
        val parsedSource$macro$3: meta.trees.Origin.ParsedSource = new scala.meta.trees.Origin.ParsedSource(scala.meta.inputs.Input.String.apply("scala3"))(dialect$macro$2);
        scala.meta.Importee.Name.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$3, 0, 3), scala.meta.Name.Indeterminate.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$3, 1, 2), "scala3")(scala.meta.dialects.`package`.Scala3))(scala.meta.dialects.`package`.Scala3)
      }
    };
    {
      val dialect$macro$6: meta.dialects.Scala213.type = meta.this.Dialect.current;
      val parsedSource$macro$7: meta.trees.Origin.ParsedSource = new scala.meta.trees.Origin.ParsedSource(scala.meta.inputs.Input.String.apply("default"))(dialect$macro$6);
      scala.meta.Importee.Name.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$7, 0, 3), scala.meta.Name.Indeterminate.Initial.apply(scala.meta.trees.Origin.Parsed.apply(parsedSource$macro$7, 1, 2), "default")(meta.this.Dialect.current))(meta.this.Dialect.current)
    }
  }
}
```

**Comment by bjaglin** [comment]
I used an import instead of an implicit val, as suggested by [the error message](https://github.com/scalameta/scalameta/blob/2a21bd8ec5c8403e5acb4047f98d161a8ec8e9f9/scalameta/quasiquotes/shared/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala#L132-L166):
> quasiquotes.scala:5: error: dialect of type scala.meta.Dialect is not supported by quasiquotes (to fix this, import something from scala.meta.dialects, e.g. scala.meta.dialects.Scala213)

**Comment by kitbellew** [comment]
@bjaglin thank you very much! as a result, i merged this one and created another follow-up: #3553.

**Pull request merged**
