### PR TITLE
ScannerTokens: use RegionForParens on LeftArrow

### LINKED ISSUE #3713: Parser fails when multiline and one condition wrapped in parenthesis
I was trying to fix it, but it touches whitespace issues which I am not super confident about:
```

  test("issue-metals") {
    runTestAssert(
      """|
         |for (m <- decls
         |    if oneCond
         |      && (cond)
         |      && satisfiable) {}
         |
         |""".stripMargin,
      Some("for (m <- decls; if oneCond && cond && satisfiable) {}")
    )(Term.For(
      List(
        Enumerator.Generator(Pat.Var(Term.Name("m")), Term.Name("decls")),
        Enumerator.Guard(Term.ApplyInfix(
          Term.ApplyInfix(
            Term.Name("oneCond"),
            Term.Name("&&"),
            Type.ArgClause(Nil),
            Term.ArgClause(List(Term.Name("cond")), None)
          ),
          Term.Name("&&"),
          Type.ArgClause(Nil),
          Term.ArgClause(List(Term.Name("satisfiable")), None)
        ))
      ),
      Term.Block(Nil)
    ))
  }
```

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #3713.

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Thanks for looking into that!

**Comment by kitbellew** [comment]
@tgodzik it occurred to me that `=` probably fails the same way. will need to look more.

**Comment by tgodzik** [comment]
Ach, actually I found another case, which I thought was the same:
```
"""|
         | for (thread <- allThreads
         |        if thread.getThreadState() == state
         |          && thread.getThreadId() != myId) {}
         |""".stripMargin
```

**Comment by kitbellew** [comment]
seems to work for me, this last example. what are you seeing? are indents exactly as you specified?

**Comment by tgodzik** [comment]
I am using this test case:
```
  test("issue-metals") {
    runTestAssert(
      """|
         | for (thread <- all
         |        if cond1 
         |           && thread.cond) {
         |      }
         |""".stripMargin,
      Some("for (thread <- all; if cond1 && thread.cond) {}")
    )(Term.For(
      List(
        Enumerator.Generator(Pat.Var(Term.Name("thread")), Term.Name("all")),
        Enumerator.Guard(Term.ApplyInfix(
          Term.Name("cond1"),
          Term.Name("&&"),
          Type.ArgClause(Nil),
          Term.ArgClause(List(Term.Select(Term.Name("thread"), Term.Name("cond"))), None)
        ))
      ),
      Term.Block(Nil)
    ))
  }
```

**Comment by kitbellew** [comment]
still works. how did you set it up? you are using `runTestAssert` without a generic, which type is it using? also, what's the dialect? did you create a new `.scala` file, or added it to an existing one?

**Comment by tgodzik** [comment]
Huh, I am confused. Opened a PR to see if maybe I have something weird set up

https://github.com/scalameta/scalameta/pull/3715

**Pull request merged**
