### PR TITLE
Misc build improvements

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
I've made mistakes in the past when dealing with the source paths for tests, but I checked this time: DialectSuite still runs:

```
> scalameta/testOnly scala.meta.tests.dialects.DialectSuite
[info] DialectSuite:
[info] - Dialect.current
[info] ScalaTest
[info] Run completed in 120 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 2 s, completed 11-Sep-2016 18:00:25
```

**Comment by dwijnand** [comment]
Similar improvements can be made in scalameta/paradise (or should I do scalamacros/paradise and then you forward merge?).

But I'll wait for feedback here first.

**Comment by xeno-by** [comment]
Thanks a lot for your SBT wisdom! Merging.

It'll be very useful if you could upgrade our paradise builds too!

**Comment by dwijnand** [comment]
Independently both do you prefer? I'm happy to do that, just checking.

**Comment by dwijnand** [comment]
Both = scalamacros/paradise & scalameta/paradise

**Comment by xeno-by** [comment]
I think independently would be better. Our codebases have already diverged, so let's keep the changes separate.

**Pull request merged**
