### PR TITLE
Bump npm version

### PR DESCRIPTION
**Pull request by gabro**
Published as 2.0.0-RC3 on https://www.npmjs.com/package/scalameta-parsers

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you!

**Comment by olafurpg** [comment]
Seems you haven't signed the CLA yet @gabro, 

> Go to https://www.lightbend.com/contribute/cla/scala and then resubmit this pull request

https://travis-ci.org/scalameta/scalameta/jobs/274092719#L584

Appveyor is having problems again 😞  but we can ignore that here.

**Comment by gabro** [comment]
> Seems you haven't signed the CLA yet @gabro,

odd, is this a new thing? I've contributed some PRs before.

Anyway, signed ;)

**Comment by olafurpg** [comment]
The script was misconfigured in CI for a short period :/ anyways, thanks!

**Comment by olafurpg** [comment]
I want to investigate first why appveyor is failing before merging.

**Comment by gabro** [comment]
No problem, this isn't blocking at all.

**Comment by olafurpg** [comment]
FYI https://github.com/scalameta/scalameta/releases/tag/v2.0.0 🎉

**Comment by gabro** [comment]
Yay! I'll publish 2.0.0 final then!

--
gabriele
~ buildo

**Comment by xeno-by** [comment]
@olafurpg @gabro What do we do about this pull request?

**Comment by olafurpg** [comment]
Once 2.0.1 is out on npm then we can merge this I guess, wdyt @gabro ?

**Comment by gabro** [comment]
Yep, sorry for leaving this hanging.

I've bumped the npm version to 2.0.1 and published it on npm.

This can be merged now!

**Pull request merged**
