### PR TITLE
2.x rebase

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
Hmm looks like the build is stuck. I'll just merge, because I need the artifact to proceed with paradise 4.x. I have verified that the tests run locally.

**Comment by olafurpg** [comment]
Hmmm, I wonder what caused the ci to freeze :/ I restarted the build just to see if it was random or a pattern.

**Comment by olafurpg** [comment]
Oh well, the ref doesn't exist anymore. Let's keep an eye out for if this happens again. Seems `2.x` ran fine after merge http://drone.geirsson.com:8001/scalameta/scalameta/72

**Pull request merged**
