### PR TITLE
Add .fold, .toOption, and .toEither to Parsed and Tokenized ADTs

### PR DESCRIPTION
**Pull request by andyscott**
This adds `fold`, `toOption`, and `toEither` methods to `Parsed`.

Additionally, all methods were updated to be implemented in terms of `fold`.

I haven't added any new tests for `toOption` and `toEither` as I'm still getting familiar with the codebase's organization.

### CODE REVIEW

**Comment by xeno-by** [comment]
This is useful. Thanks! Following @olafurpg, I'd also like to see the same changes applied to `Tokenized`.

**Comment by andyscott** [comment]
I'll put together a PR for the same changes for `Tokenized`.

**Comment by andyscott** [comment]
I went ahead and gave `Tokenized` the same treatment.

**Comment by xeno-by** [comment]
LGTM. Feel free to merge once tests pass.

**Comment by olafurpg** [comment]
Thank you @andyscott !

**Pull request merged**
