### PR TITLE
Support & Types in Dotty

### PR DESCRIPTION
**Pull request by howyp**
Adds support for intersection types from Dotty, contributing to #269.

### CODE REVIEW

**Comment by howyp** [comment]
Scala CLA signed now

**Comment by smarter** [comment]
Note that in Dotty, the type `A with B` is a valid but deprecated way to write `A & B`, except when in a extends clause like `class X extends A with B` where the linearization order matters (and writing `class X extends A & B` would be invalid).

**Comment by xeno-by** [comment]
Thanks a lot for your contribution!

I tried to restart the CI job, but without particular success. I'm travelling now, so I don't have much time, so how about you resubmit the PR please?

**Comment by howyp** [comment]
yeah, I couldn't get the job to restart either! re-creating the PR now.

**Pull request closed without merging**
