### PR TITLE
Update metac/metap aliases to use v4.0.0-M10

### PR DESCRIPTION
**Pull request by jozi-k**
When updating also metacp, I get `unsupported argument .` error

### CODE REVIEW

**Comment by jozi-k** [comment]
What about the `metacp` error?

**Comment by olafurpg** [comment]
Have you tried the `metacp` instructions in #1757 ? The arguments are different than in the older version.

**Comment by jozi-k** [comment]
Cool and thanks! I made it work, shall I open PR to your repo?

**Comment by olafurpg** [comment]
Great! We'll merge #1757 once we get an LGTM from another maintainer :)

**Pull request closed without merging**
