### PR TITLE
add ScalaTs to build-with-scalameta page

### PR DESCRIPTION
**Pull request by swachter**

### CODE REVIEW

**Comment by swachter** [comment]
signed cla

**Comment by olafurpg** [comment]
Thank you for this contribution! The CLA check is failing, otherwise looks good
```
 + echo 'Pull request submitted by swachter'
++ curl -s https://www.lightbend.com/contribute/cla/scala/check/swachter
++ jq -r .signed
+ signed=false
+ '[' false = true ']'
+ echo 'CLA check for swachter failed'
+ echo 'Please sign the Scala CLA to contribute to Scalameta'
+ echo 'Go to https://www.lightbend.com/contribute/cla/scala and then resubmit this pull request'
+ exit 1
CLA check for swachter failed
Please sign the Scala CLA to contribute to Scalameta
Go to https://www.lightbend.com/contribute/cla/scala and then resubmit this pull request
##[error]Process completed with exit code 1.
```

**Comment by olafurpg** [comment]
I can restart the CI once you have signed the CLA

**Comment by tgodzik** [comment]
The CLA is already signed, restarted and it's all green!

**Pull request merged**
