### PR TITLE
add binary literals support

### PR DESCRIPTION
**Pull request by kasiaMarek**
SIP: https://docs.scala-lang.org/sips/binary-integer-literals.html
Scala 2: https://github.com/scala/scala/pull/10656
Scala 3: https://github.com/lampepfl/dotty/pull/19551

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Lgtm! @kitbellew do you see any issues? Should be a noop change for scalafmt

**Comment by kitbellew** [comment]
i looked at the two threads on scala repo, it seems that the feature is only in 2.13 but not in dotty (and so definitely not in 3.0-2 but could be added later to whatever next milestone is).

should we disable this flag in scala30 dialect (which likely derives from scala213) and perhaps reenable in scala3future?

**Comment by kasiaMarek** [comment]
> should we disable this flag in scala30 dialect (which likely derives from scala213) and perhaps reenable in scala3future?
I think that is what I did.

**Comment by Kordyjan** [comment]
It is worth noting that this is not something that is present in any released version of Scala 3. It will become part of the language in 3.5.

**Comment by tgodzik** [comment]
It's currently in the Scala3Future dialect, so this should be safe

**Pull request merged**
