### PR TITLE
InteractiveSemanticdb doesn't get diagnostics for unused imports in 2.13

### PR DESCRIPTION
**Pull request by mlachkar**
When compiling on-demand with `new compiler`, even if I set scalacOptions, I cannot get diagnostics at least for Unused imports. 
The test shows that diagnostics is empty. 
I need some help on this issue. We use it in Scalafix, and I noticed that since 2.13, it's not working correctly anymore. Do you have any hints on how to pass scalacOptions correctly to the compiler on 2.13.

### CODE REVIEW

**Comment by tgodzik** [comment]
This might also have something with the SemanticdbReporter class. We pack the default reporter into there and maybe the warnings don't get forwarded?

**Comment by mlachkar** [comment]
I agree it may be the reporter, but I don't know how to validate it's the root cause and /fix it.

**Comment by tgodzik** [comment]
I can try to help out later today.

**Comment by tgodzik** [comment]
Tried digging into it today and it seems running `askLoadedTyped` is no longer reporting any warnings. If I try to run the compilation via Global they seem to be reported properly. Might be an issue in the compiler?

**Comment by mlachkar** [comment]
This PR has already been merged in 2.13.2, and the tests here at least are still not passing in 2.13.2 nor 2.13.3.
In this test, `new StoreReporter()` is used as a reporter. Do you advise another reporter?

**Comment by tgodzik** [comment]
> This PR has already been merged in 2.13.2, and the tests here at least are still not passing in 2.13.2 nor 2.13.3.
> In this test, `new StoreReporter()` is used as a reporter. Do you advise another reporter?

I am not sure if the reporter is the issue. I am able to get warnings if I try to compile the file not just get type information.

**Comment by tgodzik** [comment]
Fixed by https://github.com/scalameta/scalameta/pull/2216

**Pull request closed without merging**
