### PR TITLE
Support MatchType for Scala3

### PR DESCRIPTION
**Pull request by tanishiking**
Extract match_type part from https://github.com/scalameta/scalameta/pull/2414

Now it's time to merge at least for `MatchType` as https://github.com/lampepfl/dotty/pull/14608 is ready to merge :)

Let me work on metap implementation for `MatchType` in separate PR.

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
LGTM!

**Comment by kitbellew** [comment]
@tanishiking started getting these warnings:
```
[warn] .../scalameta/semanticdb/metap/src/main/scala/scala/meta/internal/metap/SymbolInformationPrinter.scala:175:9: match may not be exhaustive.
[warn] It would fail on the following input: MatchType(_, _)
[warn]         tpe match {
[warn]         ^
...
[warn] .../scalameta/tests/jvm/src/test/scala/scala/meta/tests/metacp/MetacpOps.scala:43:40: match may not be exhaustive.
[warn] It would fail on the following input: MatchType(_, _)
[warn]     def visitType(tpe: s.Type): Unit = tpe match {
[warn]                                        ^
```

**Comment by tgodzik** [comment]
> Let me work on metap implementation for MatchType in separate PR.

It will get updated later on, it should not be an issue currently.

**Comment by tanishiking** [comment]
Thanks! I will work on later

**Comment by tanishiking** [comment]
I'll work on the followup PR (metap support)

**Pull request merged**
