### PR TITLE
[WIP] upgrade sbt to 1.1.6 (from 0.13.17)

### PR DESCRIPTION
**Pull request by SethTisue**
not for merge. I'm getting:

```
error: java.lang.NoClassDefFoundError: scalapb/GeneratedEnum
```

I've never used scalapb before, so I think it would be better if someone else sorted that (and any other remaining issues) out

hopefully the progress I did make on this will be helpful! I won't be continuing further with it; feel free to leave the PR open or close it

### CODE REVIEW

**Comment by SethTisue** [comment]
perhaps relevant to the scalapb thing is https://github.com/scalameta/scalameta/issues/1615

**Comment by xeno-by** [comment]
Thank you, @SethTisue! I'll leave this to Olaf (who's currently on vacation), since he's our resident sbt expert.

**Comment by xeno-by** [comment]
I'll be closing until Olaf is back. Thanks again for getting the ball rolling!

**Comment by olafurpg** [comment]
Thank you @SethTisue for starting this! We haven't considered upgrading yet since there hasn't been motivation for it yet. I am excited about the new cross-building functionality that's expected in sbt 1.2 so that might be a good time to do the upgrade. The upgrade would also allow us to replace custom release code with https://github.com/olafurpg/sbt-ci-release (which relies on nice improvements in sbt 1)

**Pull request closed without merging**
