### PR TITLE
Cross build for Scala 2.13

### LINKED ISSUE #1873: Publish for 2.13
2.13.0-RC1 support is already done (https://github.com/scalameta/scalameta/pull/1870) so it should be a matter of testing that it still works and publishing.

Currently blocked by scalapb (which has merged 2.13 on master a couple of hours ago, but has not published artifacts yet)

### PR DESCRIPTION
**Pull request by gabro**
Closes #1873 

This is a minor followup from #1870. 

Tests run ok on my machine, let's wait for the CI 🙏

### CODE REVIEW

**Comment by gabro** [comment]
@olafurpg it seems we're missing the shaded version of fastparse for 2.13.0. Any instructions on how to publish it?

**Comment by olafurpg** [comment]
Aww shoot. I publish it manually.

**Comment by olafurpg** [comment]
We only need the utils and fastparse modules, we can reuse the v1.0.1 version number.

**Comment by olafurpg** [comment]
I’ll try to do it later once I’m back at my computer.

**Comment by gabro** [comment]
Thanks! Let me know when it's done and I'll restart the CI job.

**Comment by olafurpg** [comment]
Just restarted the build. Resolution may still fail since it takes ~30 minutes to sync to Maven and the release just finished now
```
coursier fetch org.scalameta:fastparse_2.13:1.0.1 -r sonatype:public
```

**Comment by gabro** [comment]
Ok, dependencies are all good now. I've just forgot to rename a 2.13.0-RC1 directory to 2.13.0, which is causing the current build failure. I'll fix it later when I'm at a computer

**Pull request merged**
