### PR TITLE
DRY up the dialects. Fixes #661

### LINKED ISSUE #661: Reorganize dialects
I propose to change `Dialect` from an `@root` ADT into a case class (or `@data`). Benefits

- Possible to create custom dialect with `.copy`, eliminates the need for https://github.com/scalameta/scalameta/pull/653
- Less boilerplate in adding new dialects, preventing copy-pasta errors https://github.com/scalameta/scalameta/pull/660/commits/cf8618b30cb9a26f69eb53547b82bd8d66957cd9
- More readable code, for example, `val Scala212 = Scala211.copy(allowTrailingComma = true, allowLiteralTypes = true)`

I suspect dialects will only continue to become more complicated with Typelevel/Lightbend scala + sbt + paradise + "next big thing"

### PR DESCRIPTION
**Pull request by dwijnand**
An initial solution, before Olaf's concrete suggestions in #661.

### CODE REVIEW

**Comment by xavier-fernandez** [comment]
Will rebase the PR https://github.com/scalameta/scalameta/pull/659 onto this once it is merged :)

**Comment by dwijnand** [comment]
"But, but, sbt is, like, _not_ Scala"

Yes and no, it's `Scala210` but with `allowToplevelTerms = true`:

```scala
@leaf implicit object Sbt0137 extends DelegatingDialect {
  def name = "Sbt0137"
  def delegate = Scala210
  override def allowToplevelTerms = true
}
```

**Comment by olafurpg** [comment]
I personally would love to have `.copy`, since for example in scalafmt I want to use a dialect that allows pretty much everything. It could be as simple as

```scala
@ case class Dialect2(allowTopLevelTerms: Boolean)(implicit private val sourceName: sourcecode.Name) {
    def name: String = sourceName.value
  }
defined class Dialect2
@ object Dialect2 {
    implicit val Scala210 = new Dialect2(
      allowTopLevelTerms = false
    )
    implicit val Sbt0137 = Scala210.copy(allowTopLevelTerms = true)
  }
defined object Dialect2
@ Dialect2.Sb
Sbt0137
@ Dialect2.Sbt0137.name
res7: String = "Sbt0137"
```

PS. sourcecode is already a dependency

**Comment by xeno-by** [comment]
I second @olafurpg's suggestion.

**Comment by olafurpg** [comment]
After trying to get the case class approach to work I've changed my mind and now I'm leaning more towards the approach taken by @dwijnand in this PR. See https://github.com/scalameta/scalameta/commit/1a451a339e9305a613e751de296f47915a5fc923#commitcomment-20830673 for where I got stuck with the other approach.

**Comment by dwijnand** [comment]
Started working on this. But changing the dialects to be values instead of types requires a few things to change. Particularly I've got to find a way to rework `Dialect.all`.

**Comment by dwijnand** [comment]
Right, it's nothing to do with using `@data` or with making sure `Dialect.all` returns the standard dialects: I'm hitting the compile errors you were hitting now.

**Comment by dwijnand** [comment]
@xeno-by Have you taken this task or would you like for me to keep looking at it?

**Comment by xeno-by** [comment]
@dwijnand I will fix the related macro errors and follow this through.

**Comment by xeno-by** [comment]
Superseded by #678.

**Pull request closed without merging**
