### PR TITLE
ScalametaParser: allow `using` even in scala 2

### LINKED ISSUE #2785: Accept and ignore using in args for Scala 2
References https://github.com/scala/scala/pull/10064

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #2785.

### CODE REVIEW

**Comment by dos65** [comment]
@kitbellew there is a failure in community-build `scala.meta.parser.dotty.CommunityDottySuite`

**Comment by kitbellew** [comment]
> @kitbellew there is a failure in community-build `scala.meta.parser.dotty.CommunityDottySuite`

thank you, fixed now.

**Review by dos65 — APPROVED** [review]
:+1:

**Comment by kitbellew** [comment]
@tgodzik does this look ok to you?

**Review by tgodzik — APPROVED** [review]
LGTM! Thanks for working on this, I totally forgot about this one.

**Pull request merged**
