### PR TITLE
Dialect: add useInfixTypePrecedence flag in scala3

### LINKED ISSUE #2315: [Scala 3] Enable infix type precedence
Based on input from @smarter :
>To parse Scala 3 correctly there's another subtle difference that needs to be handled: infix type applications are parsed following precedence rules, like infix term applications, for example:
```scala
class ^[A, B]
trait Test {
  def foo: String Map Int ^ Double
}
```
>In Scala 2, the type of foo is (String Map Int) ^ Double aka ^[Map[String, Int], Double] but in Scala 3 it's String Map (Int ^ Double) aka Map[String, ^[Int, Double]], there's an unmerged PR implementing this for Scala 2: scala/scala#6147

This means we would need to apply similar mechanism that we use for terms to types. Something akin to:

https://github.com/scalameta/scalameta/blob/6c0a370cc278d473588f973c436d8378a691d2b1/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L2695

It should be possibly easier than normal terms, but will not trivial at all.

### PR DESCRIPTION
**Pull request by kitbellew**
Fixes #2315.

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
LGTM! Great work! I was a bit afraid to delve into this one :sweat_smile:

**Comment by kitbellew** [comment]
> LGTM! Great work! I was a bit afraid to delve into this one 😅

turned out to be quite simple. largely a copy of the method just above, but it did let me look into his pattern infix was implemented.

(and i found a minor bug with pattern while looking, will send you soon.)

p.s. all quiet on the western front? are people feeling safe in polska?

**Comment by tgodzik** [comment]
> p.s. all quiet on the western front? are people feeling safe in polska?

I think a few days were scary for people in Poland, but now it's mostly just hectic trying to make sure that people are being helped.

**Comment by kitbellew** [comment]
> > p.s. all quiet on the western front? are people feeling safe in polska?
> 
> I think a few days were scary for people in Poland, but now it's mostly just hectic trying to make sure that people are being helped.

are you talking about ukrainian refugees? are they finding their way into poland?

**Comment by tgodzik** [comment]
> > > p.s. all quiet on the western front? are people feeling safe in polska?
> > 
> > 
> > I think a few days were scary for people in Poland, but now it's mostly just hectic trying to make sure that people are being helped.
> 
> are you talking about ukrainian refugees? are they finding their way into poland?

yes, there is almost 2 milion people who came through the polish boarder alone and some are staying while other are moving to other european countries. All of them are quite exhausted and need help.

**Pull request merged**
