### PR TITLE
chore: Test ExpectSuite under Scala 2.13

### PR DESCRIPTION
**Pull request by tgodzik**
I split the expect file for Scala 2.12 and Scala 2.13 and it seems we get proper diagnostics for both :thinking:

### CODE REVIEW

**Comment by tgodzik** [comment]
@bjaglin we haven't been testing diagnostics under 2.13 it seems (though I could have sworn we had at least a couple of tests), but it seems diagnostics are present in the expected output. Anything specific about those tests in https://github.com/scalameta/scalameta/issues/2993 ?

Maybe we broke the parser for that file?

**Comment by tgodzik** [comment]
On the other hand I can reproduce that locally :thinking: Will need to dig in more

**Comment by tgodzik** [comment]
Ach, actually I used the wrong file :/  We can check if the results here change after https://github.com/scalameta/scalameta/pull/2996

**Review by kitbellew — APPROVED** [review]

**Comment by kitbellew** [comment]
@tgodzik is it possible that this should have been rebased on top of #2996 (which was merged a day earlier)? i am getting test errors in `ExpectSuite` from the commit tagged with release v4.7.1.

**Comment by tgodzik** [comment]
> @tgodzik is it possible that this should have been rebased on top of #2996 (which was merged a day earlier)? i am getting test errors in `ExpectSuite` from the commit tagged with release v4.7.1.

Wait, I checked that and it seemed to work ok locally. I should have rebased :sweat: I will raise a PR

**Pull request merged**
