### PR TITLE
fix the build for 2.12

### PR DESCRIPTION
**Pull request by xeno-by**

### CODE REVIEW

**Comment by xeno-by** [comment]
@fommil Is there way to get java 1.8 out of `ensime/ensime:v2.x-cache`?

**Comment by fommil** [comment]
Use jenv. Create a .java-version file with the version of Java you want.

**Comment by fommil** [comment]
I don't use jenv global, just create the file. It should be the default, do you maybe have one already? Have a look in pcplod's build do so how i do it.

**Comment by xeno-by** [comment]
@fommil Thank you! It worked.

**Pull request merged**
