### PR TITLE
Add support for Java 11

### PR DESCRIPTION
**Pull request by olafurpg**
Java 11 works only Scala 2.12.7, it crashes on 2.11.12 since ASM throws
an error when parsing JDK 11 classfiles. The main changes in this
commit are:

- detect `jrt:/` file system on Java 9+ and use that for JDK classpath
- add `includeJdk: Boolean` option to construct symbol tables,
  this flag correctly takes care of Java 8 and 11 differences.
- remove `Libraries.jdk` since the JDK can no be longer typed as
  `AbsolutePath` on Java 11.
- use `String.linesIterator` instead of `String.lines`, since Java 11
  added `String.lines` so the extension method no longer binds.
- update build.sbt to load on Java 11

### CODE REVIEW

**Comment by olafurpg** [comment]
cc/ @SethTisue might be relevant for the community build

**Comment by olafurpg** [comment]
Green CI job for JDK 11 https://travis-ci.org/scalameta/scalameta/jobs/460278830 Looking good, to validate it's truly running on jdk 11 you can see the warning here https://travis-ci.org/scalameta/scalameta/jobs/460278830#L547-L552

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by sbt.ivyint.ErrorMessageAuthenticator$ (file:/home/travis/.sbt/boot/scala-2.10.7/org.scala-sbt/sbt/0.13.17/ivy-0.13.17.jar) to field java.net.Authenticator.theAuthenticator
WARNING: Please consider reporting this to the maintainers of sbt.ivyint.ErrorMessageAuthenticator$
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by SethTisue** [comment]
> cc/ @SethTisue might be relevant for the community build

(Scalameta isn't part of the 2.11 community build. it's already green in the 2.12-on-JDK11 build)

**Comment by olafurpg** [comment]
You can add it to the JDK 11 build now if you want

**Comment by SethTisue** [comment]
> You can add it to the JDK 11 build now if you want

eh?

**Comment by olafurpg** [comment]
I'm sorry I saw "non-jdk11" instead of "on-jdk11". Nevermind then, but at least this pr made a lot more code compile and tests pass FWIW

**Comment by SethTisue** [comment]
@olafurpg I took a closer look just now and I see that in the community build, we have scalameta forked, and JDK 11 friendliness was one motivation for the fork, so this should help us unfork, down the road. thank you!

(I say "down the road" because historically, scalameta master has been too fragile for the community build to track, we've had to carefully coordinate upgrading scalameta, scalafix, and scalafmt all in tandem)

I've left this breadcrumb for later: scala/community-builds@e81500b2bab3606a08f008077a788e131fdc0689

**Comment by olafurpg** [comment]
Thanks for the clarification. We're slowly reaching more stability, semanticdb-scalac no longer does evil runtime reflection making compiler version upgrades easier and scalafmt/scalafix are on the latest scalameta version.

**Pull request merged**
