### PR TITLE
add union types (A | B)

### PR DESCRIPTION
**Pull request by liufengyun**
Add union types (A | B).

This is a first try-and-play commit. Need to systemise what AST are missing and attack them one by one. Review @xeno-by .

### CODE REVIEW

**Comment by xeno-by** [comment]
Thank you for your contribution! On Thursday, I'm leaving for vacation until 5 Oct, which is probably when I'll get to review this PR.

**Comment by liufengyun** [comment]
Makes perfect sense to me. Congrats and enjoy your holiday!

**Comment by jvican** [comment]
Related to https://github.com/scalameta/scalameta/issues/269.

**Comment by xeno-by** [comment]
Superseded by https://github.com/scalameta/scalameta/pull/506

**Pull request closed without merging**
